name: stormworkflow
channels:
  - conda-forge
dependencies:
  - cartopy
  - cf-python
  - cfdm
  - cfgrib
  - cfunits
  - colored-traceback
  - cmocean
  - esmf
  - esmpy
  - fiona
  - gdal
  - geoalchemy2
  - geopandas
  - geos
  - hdf5
  - importlib_metadata<8  # Fix issue with esmpy Author import
  - matplotlib
  - mpi4py
  - netcdf4
  - numpy>=2
  - numba
  - ocsmesh==1.5.3
  - pandas
  - pip
  - proj
  - pyarrow
  - pygeos
  - pyproj
  - python<3.12
  - pytz
  - shapely>=2
  - rasterio
  - requests
  - rtree
  - scipy
  - seawater
  - typing-extensions
  - tqdm
  - udunits2
  - utm
  - xarray
